version: '3'
services:
  app: 
    container_name: fastfeet-api
    build: .
    ports: 
      - "3333:3333"
    depends_on:
      - postgres
      - redis
    links: 
      - postgres
      - redis
    command: npm run dev
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    environment:
      PORT: 3333
  jobs:
    container_name: fastfeet-jobs
    image: node:dubnium-alpine
    working_dir: /usr/jobs
    command: sh -c "npm install && npm run build && npm run queue"
    volumes:
      - .:/usr/jobs
    links:
      - postgres
      - redis
    environment:
      NODE_ENV: dev
      DB_HOST: postgres
  postgres:
    container_name: fastfeet-database
    image: postgres:11
    ports:
      - "5432:5432"
    environment: 
      POSTGRES_DB: fastfeet
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: elefante
  redis:
    image: redis:alpine
    expose:
      - 6379